### ISSUE TITLE
when will tiktok dance dataset release?

### ISSUE THREAD

**Issue by lucasjinreal** [L-YeZhu/D2M-GAN#1]

**Comment by L-YeZhu** [comment]
Hi, I will need to confirm the releasing procedure with our coauthors from company's side, I will leave the issue open and let you know when the dataset is ready to be released.

**Comment by lucasjinreal** [comment]
thank u

**Comment by L-YeZhu** [comment]
I have released the preprocessed TikTok data as well as the full annotations (which includes the download link from YouTube), some of the links might not work due to the videos may have been removed or made private, if you need the raw videos please further let me know.
