### ISSUE TITLE
suspect a mistake in the paper

### ISSUE THREAD

**Issue by Aolin-MIR** [L-YeZhu/D2M-GAN#2]
While reading the paper,  in page2 the section with regrard to the hinge loss function, I think you should use max() instead min()

**Comment by L-YeZhu** [comment]
Hi! Thanks for your interest and careful reading! I have checked the paper regarding the hinge loss, and think it seems to be right to use Min(0,1 - D)? (if that is the place you refer to)
Here are some refs: https://arxiv.org/pdf/1910.06711.pdf  http://csuh.kaist.ac.kr/easit/TN4_hinge_GAN.pdf
