### ISSUE TITLE
Potential Bug Report

### ISSUE THREAD

**Issue by JustinYuu** [L-YeZhu/D2M-GAN#3]
Hi, I'd like to report a bug (maybe) in l.96, class VAMDataset, d2m/dataset.py, where the directories of motion files are not post-processed like the audio/video files above. Adding `self.motion_files = [Path(motion_files).parent / x for x in self.motion_files]` could be a solution?

**Comment by L-YeZhu** [comment]
Hi, thank you for pointing this out. I have fixed it and updated the script.
