### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by liangx66** [L-YeZhu/D2M-GAN#4]
Hi author, Nice Work! 
I have tried the generation process on AIST++, it seems that the generated samples have the basic rhythm but don't sound real enough. I don't know what's the problem with it. Is it the reason for high level model setting? And I wonder if you could share the pre-trained models of low level for quick start?

**Comment by L-YeZhu** [comment]
Hi, thanks for your interest in our work.
It is true that sometimes the rhythms may come earlier than the melody part, leaving it with a little bit of longer training time should help with mitigating this problem. In the meanwhile, I can search for the low level checkpoints to share.

**Comment by liangx66** [comment]
thank you for your reply

**Comment by L-YeZhu** [comment]
You can download the checkpoints for the low level here: [Generator](https://drive.google.com/file/d/1aYorY23XfGumBwro58dm6jMqZ_j-4fEy/view?usp=sharing) and [Motion encoder](https://drive.google.com/file/d/1Wg0H8RxogjrOd2ey95NqFEyvEjUDSIFP/view?usp=sharing).
