### ISSUE TITLE
extract feature

### ISSUE THREAD

**Issue by borishanzju** [L-YeZhu/D2M-GAN#5]
Hello, how do you extract the motion features and visual features of the video, do you have a specific reference link? Looking forward to your reply

**Comment by L-YeZhu** [comment]
Hi. For the motion features, we use the [Openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose), and for the visual features, we use the pre-trained [I3D models](https://github.com/piergiaj/pytorch-i3d). Hope it helps
