### ISSUE TITLE
Problem about motion shape

### ISSUE THREAD

**Issue by robingg1** [L-YeZhu/D2M-GAN#7]
I am wondering why the motion is in shape of (120*219) for the preprocessed data. Where did 219 come from ?

**Comment by L-YeZhu** [comment]
Hi,

We follow the work [AIST++](https://google.github.io/aistplusplus_dataset/factsfigures.html) for the pre-processing of the motion data. As described in this paper, they parse the videos into 60 fs and extract body key points in total 219 dim. So the shape corresponds to the motion data in 2 s. Hope it helps!

**Comment by robingg1** [comment]
Thanks a lot!
